backend = "egl";
vsync = true;

# blur Pijulius (Kawase)
blur: {
  method = "dual_kawase";
  strength = 5;
  background = true;
};

# Transparency
inactive-opacity = 0.85;
active-opacity = 1.0;

# Corner
corner-radius = 12;

# Fading 
fading = true;
fade-delta = 5;
