[background]
# wallpaper copied to /etc/greetd/ so the greeter user can read it
path = "/etc/greetd/wallpaper.jpg"
fit  = "Cover"

[gtk]
application_prefer_dark_theme = true
font_name                     = "JetBrainsMono Nerd Font Mono 13"
icon_theme_name               = "Adwaita"
theme_name                    = "Adwaita"
