wallpaper {
    monitor = eDP-1
    path = /home/gus/media/pictures/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/gus/media/pictures/wallpapers/wallpaper.jpg
    fit_mode = cover
}

splash = false
